import os
from collections import defaultdict
from datetime import datetime

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
from pymongo import MongoClient

client = MongoClient(os.getenv("MONGODB_URI", "mongodb://localhost:27017/fairgig_db"))
db = client["fairgig_db"]
users = db["users"]
earnings = db["earnings"]

app = FastAPI(title="FairGig Certificate Service")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(Exception)
async def general_exception_handler(_, exc: Exception):
    return JSONResponse(status_code=500, content={"data": None, "error": str(exc), "message": "Internal server error", "detail": "Internal server error"})


@app.get("/certificate/{workerId}", response_class=HTMLResponse)
async def certificate(workerId: str):
    worker = users.find_one({"_id": {"$eq": __import__("bson").ObjectId(workerId)}}) if len(workerId) == 24 else users.find_one({"_id": workerId})
    records = list(earnings.find({"workerId": workerId, "isVerified": True}).sort("date", 1))
    if not worker:
        return "<h1>Worker not found</h1>"

    total_verified = sum(item.get("amount", 0) for item in records)
    verified_count = len(records)
    monthly_avg = total_verified / max(1, len({(r["date"].year, r["date"].month) for r in records})) if records else 0
    bucket = defaultdict(float)
    for item in records:
        bucket[item.get("platform", "Unknown")] += item.get("amount", 0)
    top_platform = max(bucket, key=bucket.get) if bucket else "N/A"
    date_range = f"{records[0]['date'].strftime('%d %b %Y')} - {records[-1]['date'].strftime('%d %b %Y')}" if records else "N/A"
    platform_rows = "".join(
        f"<tr><td>{platform}</td><td>PKR {int(amount):,}</td></tr>" for platform, amount in sorted(bucket.items(), key=lambda item: item[1], reverse=True)
    )
    certificate_date = datetime.utcnow().strftime("%d %b %Y")

    return f"""
    <html><head><title>FairGig Certificate</title>
    <style>
      body {{ font-family: Arial, sans-serif; background: #f8fafc; padding: 20px; }}
      .sheet {{ position: relative; max-width: 900px; margin: 0 auto; background: white; padding: 36px; border: 1px solid #e2e8f0; }}
      .watermark {{ position: absolute; top: 45%; left: 20%; transform: rotate(-30deg); font-size: 90px; opacity: 0.08; color: #4F46E5; font-weight: bold; }}
      table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
      th, td {{ border: 1px solid #e2e8f0; padding: 10px; text-align: left; }}
      .print-btn {{ background: #4F46E5; color: white; border: 0; padding: 10px 18px; border-radius: 8px; cursor: pointer; }}
      @media print {{ .print-btn {{ display: none; }} body {{ padding: 0; background: white; }} .sheet {{ border: 0; }} }}
    </style></head>
    <body>
      <div class="sheet">
        <div class="watermark">VERIFIED</div>
        <button class="print-btn" onclick="window.print()">Print Certificate</button>
        <h1>FairGig - Income Verification Certificate</h1>
        <p><strong>Worker:</strong> {worker.get('name', 'Unknown')} | <strong>City:</strong> {worker.get('city', 'N/A')} | <strong>Date:</strong> {certificate_date}</p>
        <table>
          <tr><th>Verified Earnings</th><th>Avg Monthly</th><th>Top Platform</th><th>Period</th></tr>
          <tr><td>PKR {int(total_verified):,}</td><td>PKR {int(monthly_avg):,}</td><td>{top_platform}</td><td>{date_range}</td></tr>
        </table>
        <h3>Per-platform Breakdown</h3>
        <table><tr><th>Platform</th><th>Total</th></tr>{platform_rows or '<tr><td colspan="2">No verified earnings</td></tr>'}</table>
        <p style="margin-top: 20px;">This certificate is generated by FairGig and reflects verified earnings only.</p>
      </div>
    </body></html>
    """
